changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - "**/*.spec.{js,ts,tsx}"

npmAuthToken: "${NPM_AUTH_TOKEN-emptytoken}"

packageExtensions:
  '@fluentui/foundation-legacy@*':
    peerDependencies:
      react: '*'
  '@fluentui/react-focus@*':
    peerDependencies:
      react: '*'
  '@fluentui/react@*':
    peerDependencies:
      react: '*'  
      "@types/prop-types": "*"
      prop-types: "*"
  '@fluentui/style-utilities@*':
    peerDependencies:
      react: '*'
  '@fluentui/theme@*':
    peerDependencies:
      react: '*'
  '@fluentui/utilities@*':
    peerDependencies:
      react: '*'
  '@uifabric/icons@*':
    peerDependencies:
      react: ^16
  '@uifabric/styling@*':
    peerDependencies:
      react: ^16
      "@types/react": "*"
  "@testing-library/react@*":
    dependencies:
      "@types/pretty-format": ^24.3.0
      pretty-format: 26.5.2
  "@thematic/d3@*":
    peerDependencies:
      "@types/d3-axis": "*"
  "@thematic/fluent@*":
    peerDependencies:
      "@uifabric/icons": "*"
  office-ui-fabric-react@*:
    peerDependencies:
      "@types/prop-types": "*"
      prop-types: "*"
  styled-components@*:
    dependencies:
      react-is: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
