


packageExtensions:
  "@essex-js-toolkit/themed-components@*":
    dependencies:
      "office-ui-fabric-react": "^7.147.1"
  "@essex-js-toolkit/hierarchy-browser@*":
    dependencies:
      "@babel/runtime": "^7.12.5"
    peerDependencies:
      "regenerator-runtime": "*"
      "core-js" : "*"
  "@essex-js-toolkit/thematic-lineup@*":
    dependencies:
        "lineupjs": "*"
        "tslib" : "*"
    peerDependencies:
      "lineupjs": "*"
      "tslib" : "*"
  "lineupjs@*":
    dependencies:
        "tslib" : "*"
    peerDependencies:
      "tslib" : "*"
  "@essex/webpack-config@*":
    peerDependencies:
      typescript: "*"
      worker-loader: "*"


